{
  inputs,
  lib,
  ...
}:
let
  repoLanguagesModule = {
    imports = [
      "${inputs.files}/flake-module.nix"
      inputs.git-hooks.flakeModule
      inputs.treefmt-nix.flakeModule
    ];

    perSystem =
      { pkgs, config, ... }:
      let
        cfg = config.repoLanguages;

        languageType = lib.types.submodule (
          { config, ... }:
          {
            options = {
              enable = lib.mkEnableOption "language support";

              lsps = lib.mkOption {
                type = lib.types.listOf lib.types.package;
                default = [ ];
                description = "Language server packages for this language.";
              };

              tooling = lib.mkOption {
                type = lib.types.listOf lib.types.package;
                default = [ ];
                description = "Non-LSP tool packages for this language.";
              };

              gitHooks = lib.mkOption {
                type = lib.types.attrsOf lib.types.anything;
                default = { };
                description = "pre-commit hook settings for this language.";
              };

              treefmt = lib.mkOption {
                type = lib.types.attrsOf lib.types.anything;
                default = { };
                description = "treefmt-nix settings for this language.";
              };

              zed = {
                enable = lib.mkOption {
                  type = lib.types.bool;
                  default = config.enable;
                  description = "Enable Zed project settings for this language.";
                };

                settings = lib.mkOption {
                  type = lib.types.attrsOf lib.types.anything;
                  default = { };
                  description = "Zed project settings for this language.";
                };

                extensions = lib.mkOption {
                  type = lib.types.listOf lib.types.str;
                  default = [ ];
                  description = "Zed extensions for this language.";
                };
              };

              neovim = {
                enable = lib.mkOption {
                  type = lib.types.bool;
                  default = config.enable;
                  description = "Enable Neovim integration for this language.";
                };

                extraPackages = lib.mkOption {
                  type = lib.types.listOf lib.types.package;
                  default = config.lsps ++ config.tooling;
                  description = "Packages made available to Neovim for this language.";
                };

                extraLuaConfig = lib.mkOption {
                  type = lib.types.lines;
                  default = "";
                  description = "Language-specific Neovim Lua config.";
                };

                plugins = lib.mkOption {
                  type = lib.types.listOf lib.types.package;
                  default = [ ];
                  description = "Neovim plugins for this language.";
                };
              };
            };
          }
        );

        enabledLanguages = lib.attrValues (
          lib.filterAttrs (_name: language: language.enable) cfg.languages
        );
        zedLanguages = builtins.filter (language: language.zed.enable) enabledLanguages;

        languagePackages = lib.concatMap (language: language.lsps ++ language.tooling) enabledLanguages;
        jsonFormat = pkgs.formats.json { };
        zedSettings = lib.foldl' lib.recursiveUpdate cfg.zed.settings (
          map (language: language.zed.settings) zedLanguages
        );

      in
      {
        options.repoLanguages = {
          enable = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = "Enable language tooling aggregation.";
          };

          languages = lib.mkOption {
            type = lib.types.attrsOf languageType;
            default = { };
            description = "Language integrations for this repository.";
          };

          packages = lib.mkOption {
            internal = true;
            type = lib.types.listOf lib.types.package;
            default = [ ];
            description = "Packages made available to the repository development shell.";
          };

          zed = {
            settings = lib.mkOption {
              type = lib.types.attrsOf lib.types.anything;
              default = {
                load_direnv = "shell_hook";
              };
              description = "Base Zed project settings.";
            };

            settingsFile = lib.mkOption {
              type = lib.types.str;
              default = ".zed/settings.json";
              description = "Project-relative Zed settings file generated by the files module.";
            };
          };
        };

        config = lib.mkIf cfg.enable {
          repoLanguages.packages = [
            pkgs.prek
            config.treefmt.build.wrapper
            config.files.writer.drv
          ]
          ++ languagePackages;

          files.files = [
            {
              path = cfg.zed.settingsFile;
              drv = jsonFormat.generate "zed-settings.json" zedSettings;
            }
          ];

          pre-commit = {
            check.enable = true;
            settings = {
              package = pkgs.prek;
              hooks = lib.mkMerge (map (language: language.gitHooks) enabledLanguages);
            };
          };

          treefmt = lib.mkMerge (
            [
              {
                projectRootFile = "flake.nix";
              }
            ]
            ++ map (language: language.treefmt) enabledLanguages
          );
        };
      };
  };
in
{
  imports = [ repoLanguagesModule ];

  flake.flakeModules.default = repoLanguagesModule;
  flake.flakeModules.languages = repoLanguagesModule;
}
